/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppBarNoCart: typeof import('./src/components/AppBarNoCart.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    Ejercicio1: typeof import('./src/components/ejercicio1.vue')['default']
    Ejercicio2: typeof import('./src/components/ejercicio2.vue')['default']
    Ejercicio3: typeof import('./src/components/ejercicio3.vue')['default']
    Ejercicio4: typeof import('./src/components/Ejercicio4.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
